FROM docker.elastic.co/kibana/kibana:5.5.0

#RUN logstash-plugin install logstash-filter-grok
#RUN logstash-plugin install logstash-filter-translate
#RUN logstash-plugin install logstash-codec-netflow
#RUN kibana-plugin install com.floragunn:search-guard-5:5.5.0-14
