FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.0

#RUN logstash-plugin install logstash-filter-grok
#RUN logstash-plugin install logstash-filter-translate
#RUN logstash-plugin install logstash-codec-netflow
#RUN elasticsearch-plugin install  -b com.floragunn:search-guard-5:5.5.0-14
